/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/adarga-ai/pachyderm-pipeline-controller/apis/pachyderm/v1alpha1"
	scheme "github.com/adarga-ai/pachyderm-pipeline-controller/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PachydermPipelinesGetter has a method to return a PachydermPipelineInterface.
// A group's client should implement this interface.
type PachydermPipelinesGetter interface {
	PachydermPipelines(namespace string) PachydermPipelineInterface
}

// PachydermPipelineInterface has methods to work with PachydermPipeline resources.
type PachydermPipelineInterface interface {
	Create(*v1alpha1.PachydermPipeline) (*v1alpha1.PachydermPipeline, error)
	Update(*v1alpha1.PachydermPipeline) (*v1alpha1.PachydermPipeline, error)
	UpdateStatus(*v1alpha1.PachydermPipeline) (*v1alpha1.PachydermPipeline, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.PachydermPipeline, error)
	List(opts v1.ListOptions) (*v1alpha1.PachydermPipelineList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PachydermPipeline, err error)
	PachydermPipelineExpansion
}

// pachydermPipelines implements PachydermPipelineInterface
type pachydermPipelines struct {
	client rest.Interface
	ns     string
}

// newPachydermPipelines returns a PachydermPipelines
func newPachydermPipelines(c *AdargaV1alpha1Client, namespace string) *pachydermPipelines {
	return &pachydermPipelines{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the pachydermPipeline, and returns the corresponding pachydermPipeline object, and an error if there is any.
func (c *pachydermPipelines) Get(name string, options v1.GetOptions) (result *v1alpha1.PachydermPipeline, err error) {
	result = &v1alpha1.PachydermPipeline{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("pachydermpipelines").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PachydermPipelines that match those selectors.
func (c *pachydermPipelines) List(opts v1.ListOptions) (result *v1alpha1.PachydermPipelineList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.PachydermPipelineList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("pachydermpipelines").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested pachydermPipelines.
func (c *pachydermPipelines) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("pachydermpipelines").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a pachydermPipeline and creates it.  Returns the server's representation of the pachydermPipeline, and an error, if there is any.
func (c *pachydermPipelines) Create(pachydermPipeline *v1alpha1.PachydermPipeline) (result *v1alpha1.PachydermPipeline, err error) {
	result = &v1alpha1.PachydermPipeline{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("pachydermpipelines").
		Body(pachydermPipeline).
		Do().
		Into(result)
	return
}

// Update takes the representation of a pachydermPipeline and updates it. Returns the server's representation of the pachydermPipeline, and an error, if there is any.
func (c *pachydermPipelines) Update(pachydermPipeline *v1alpha1.PachydermPipeline) (result *v1alpha1.PachydermPipeline, err error) {
	result = &v1alpha1.PachydermPipeline{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("pachydermpipelines").
		Name(pachydermPipeline.Name).
		Body(pachydermPipeline).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *pachydermPipelines) UpdateStatus(pachydermPipeline *v1alpha1.PachydermPipeline) (result *v1alpha1.PachydermPipeline, err error) {
	result = &v1alpha1.PachydermPipeline{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("pachydermpipelines").
		Name(pachydermPipeline.Name).
		SubResource("status").
		Body(pachydermPipeline).
		Do().
		Into(result)
	return
}

// Delete takes name of the pachydermPipeline and deletes it. Returns an error if one occurs.
func (c *pachydermPipelines) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("pachydermpipelines").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *pachydermPipelines) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("pachydermpipelines").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched pachydermPipeline.
func (c *pachydermPipelines) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PachydermPipeline, err error) {
	result = &v1alpha1.PachydermPipeline{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("pachydermpipelines").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
