/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/adarga-ai/pachyderm-pipeline-controller/apis/pachyderm/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePachydermPipelines implements PachydermPipelineInterface
type FakePachydermPipelines struct {
	Fake *FakeAdargaV1alpha1
	ns   string
}

var pachydermpipelinesResource = schema.GroupVersionResource{Group: "adarga.ai", Version: "v1alpha1", Resource: "pachydermpipelines"}

var pachydermpipelinesKind = schema.GroupVersionKind{Group: "adarga.ai", Version: "v1alpha1", Kind: "PachydermPipeline"}

// Get takes name of the pachydermPipeline, and returns the corresponding pachydermPipeline object, and an error if there is any.
func (c *FakePachydermPipelines) Get(name string, options v1.GetOptions) (result *v1alpha1.PachydermPipeline, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(pachydermpipelinesResource, c.ns, name), &v1alpha1.PachydermPipeline{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PachydermPipeline), err
}

// List takes label and field selectors, and returns the list of PachydermPipelines that match those selectors.
func (c *FakePachydermPipelines) List(opts v1.ListOptions) (result *v1alpha1.PachydermPipelineList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(pachydermpipelinesResource, pachydermpipelinesKind, c.ns, opts), &v1alpha1.PachydermPipelineList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PachydermPipelineList{ListMeta: obj.(*v1alpha1.PachydermPipelineList).ListMeta}
	for _, item := range obj.(*v1alpha1.PachydermPipelineList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested pachydermPipelines.
func (c *FakePachydermPipelines) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(pachydermpipelinesResource, c.ns, opts))

}

// Create takes the representation of a pachydermPipeline and creates it.  Returns the server's representation of the pachydermPipeline, and an error, if there is any.
func (c *FakePachydermPipelines) Create(pachydermPipeline *v1alpha1.PachydermPipeline) (result *v1alpha1.PachydermPipeline, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(pachydermpipelinesResource, c.ns, pachydermPipeline), &v1alpha1.PachydermPipeline{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PachydermPipeline), err
}

// Update takes the representation of a pachydermPipeline and updates it. Returns the server's representation of the pachydermPipeline, and an error, if there is any.
func (c *FakePachydermPipelines) Update(pachydermPipeline *v1alpha1.PachydermPipeline) (result *v1alpha1.PachydermPipeline, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(pachydermpipelinesResource, c.ns, pachydermPipeline), &v1alpha1.PachydermPipeline{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PachydermPipeline), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePachydermPipelines) UpdateStatus(pachydermPipeline *v1alpha1.PachydermPipeline) (*v1alpha1.PachydermPipeline, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(pachydermpipelinesResource, "status", c.ns, pachydermPipeline), &v1alpha1.PachydermPipeline{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PachydermPipeline), err
}

// Delete takes name of the pachydermPipeline and deletes it. Returns an error if one occurs.
func (c *FakePachydermPipelines) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(pachydermpipelinesResource, c.ns, name), &v1alpha1.PachydermPipeline{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePachydermPipelines) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(pachydermpipelinesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.PachydermPipelineList{})
	return err
}

// Patch applies the patch and returns the patched pachydermPipeline.
func (c *FakePachydermPipelines) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PachydermPipeline, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(pachydermpipelinesResource, c.ns, name, pt, data, subresources...), &v1alpha1.PachydermPipeline{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PachydermPipeline), err
}
